import { Service, Project, Stat, Value } from "@/types";

export const services: Service[] = [
  {
    id: "advertising",
    titleAr: "الدعاية والإعلان",
    titleEn: "Advertising & Publicity",
    descAr: "حملات إعلانية مبتكرة تصل إلى جمهورك المستهدف بفاعلية عبر قنوات متعددة",
    descEn: "Innovative advertising campaigns that effectively reach your target audience across multiple channels",
    icon: "Megaphone",
  },
  {
    id: "printing",
    titleAr: "الطباعة المتعددة",
    titleEn: "Multi-Printing",
    descAr: "طباعة رقمية وأوفست بجودة عالية لتلبية جميع احتياجاتك باحترافية",
    descEn: "High-quality digital and offset printing for all your professional needs",
    icon: "Printer",
  },
  {
    id: "events",
    titleAr: "الفعاليات والمعارض",
    titleEn: "Events & Exhibitions",
    descAr: "تخطيط وتنظيم وإدارة الفعاليات والمؤتمرات والمعارض بمعايير عالمية",
    descEn: "Planning, organizing and managing events, conferences and exhibitions to global standards",
    icon: "CalendarCheck",
  },
  {
    id: "gifts",
    titleAr: "الهدايا والوسائل الترويجية",
    titleEn: "Gifts & Promotional",
    descAr: "هدايا مخصصة ووسائل ترويجية إبداعية تعزز علامتك التجارية",
    descEn: "Custom gifts and creative promotional tools that enhance your brand",
    icon: "Gift",
  },
  {
    id: "technical",
    titleAr: "التعهدات الفنية",
    titleEn: "Technical Undertakings",
    descAr: "حلول تقنية متكاملة تشمل التركيبات والإضاءة والصوتيات",
    descEn: "Integrated technical solutions including installations, lighting and sound systems",
    icon: "Settings2",
  },
  {
    id: "logistics",
    titleAr: "الخدمات اللوجستية والضيافة",
    titleEn: "Logistics & Hospitality",
    descAr: "خدمات لوجستية متكاملة وضيافة احترافية لفعالياتك ومناسباتك",
    descEn: "Integrated logistics services and professional hospitality for your events and occasions",
    icon: "Truck",
  },
];

export const projects: Project[] = [
  {
    id: "civil-defense",
    titleAr: "حفل تخريج قوات الدفاع المدني",
    titleEn: "Civil Defense Graduation Ceremony",
    client: "الدفاع المدني السعودي",
    category: "government",
    year: 2025,
    descAr: "تنظيم حفل تخريج لقوات الدفاع المدني في مكة المكرمة بمعايير بروتوكولية عالية",
    descEn: "Organizing the graduation ceremony for the Civil Defense forces in Makkah with high protocol standards",
    image: "https://wodohalroya.com/wp-content/uploads/2025/07/الدفاع-المدني.jpg",
  },
  {
    id: "king-salman",
    titleAr: "استقبال خادم الحرمين الشريفين",
    titleEn: "Reception of King Salman",
    client: "الديوان الملكي",
    category: "government",
    year: 2025,
    descAr: "استقبال خادم الحرمين الشريفين الملك سلمان بن عبدالعزيز في منطقة حائل",
    descEn: "Reception of the Custodian of the Two Holy Mosques King Salman in Hail Region",
    image: "https://wodohalroya.com/wp-content/uploads/2025/06/لقطة-شاشة-2025-04-13-183819.webp",
  },
  {
    id: "janadriyah",
    titleAr: "مهرجان الجنادرية",
    titleEn: "Al-Janadriyah Festival",
    client: "وزارة الحرس الوطني",
    category: "events",
    year: 2025,
    descAr: "المشاركة في المهرجان الوطني للتراث والثقافة (الجنادرية)",
    descEn: "Participation in the National Festival for Heritage and Culture (Al-Janadriyah)",
    image: "https://wodohalroya.com/wp-content/uploads/2025/04/لقطة-شاشة-2025-04-13-184030.png",
  },
  {
    id: "citrus-festival",
    titleAr: "مهرجان الحمضيات",
    titleEn: "Citrus Festival",
    client: "محافظة الحريق",
    category: "events",
    year: 2025,
    descAr: "تنظيم مهرجان الحمضيات الخامس في الحريق",
    descEn: "Organizing the 5th Citrus Festival in Al-Hariq",
    image: "https://wodohalroya.com/wp-content/uploads/2025/04/لقطة-شاشة-2025-04-13-184250.png",
  },
  {
    id: "university-founding",
    titleAr: "يوم التأسيس - جامعة الإمام",
    titleEn: "Founding Day - Imam University",
    client: "جامعة الإمام محمد بن سعود",
    category: "government",
    year: 2025,
    descAr: "تنظيم احتفالات يوم التأسيس في جامعة الإمام محمد بن سعود",
    descEn: "Organizing the Founding Day celebrations at Imam Muhammad bin Saud University",
    image: "https://wodohalroya.com/wp-content/uploads/2025/04/لقطة-شاشة-2025-04-13-190245.png",
  },
  {
    id: "eastern-governor",
    titleAr: "زيارة أمير المنطقة الشرقية",
    titleEn: "Eastern Province Governor Visit",
    client: "إمارة المنطقة الشرقية",
    category: "government",
    year: 2025,
    descAr: "تنظيم استقبال أمير المنطقة الشرقية في حفر الباطن",
    descEn: "Organizing the reception of the Eastern Province Governor in Hafar Al-Batin",
    image: "https://wodohalroya.com/wp-content/uploads/2025/05/3cd44a92-10d0-4cb7-9893-bef940084075-768x578.jpeg",
  },
  {
    id: "nabawi-signage",
    titleAr: "تركيب اللوحات في المسجد النبوي",
    titleEn: "Signage at Al-Masjid An-Nabawi",
    client: "رئاسة شؤون الحرمين",
    category: "government",
    year: 2025,
    descAr: "تركيب وتنفيذ اللوحات الإرشادية في المسجد النبوي الشريف",
    descEn: "Installation and execution of signage at the Prophet's Mosque",
    image: "https://wodohalroya.com/wp-content/uploads/2025/04/لقطة-شاشة-2025-04-13-184434.png",
  },
  {
    id: "sattam-university",
    titleAr: "حفل تخرج جامعة سطام",
    titleEn: "Prince Sattam University Graduation",
    client: "جامعة الأمير سطام بن عبدالعزيز",
    category: "events",
    year: 2025,
    descAr: "حفل تخرّج الدفعة الرابعة عشر من جامعة الأمير سطام بن عبدالعزيز",
    descEn: "The graduation ceremony of batch 14 at Prince Sattam bin Abdulaziz University",
    image: "https://wodohalroya.com/wp-content/uploads/2025/05/حفل-تخرج-جامعة-سطام-.jpg",
  },
  {
    id: "baha-university",
    titleAr: "حفل تخرج جامعة الباحة",
    titleEn: "Al-Baha University Graduation",
    client: "جامعة الباحة",
    category: "events",
    year: 2025,
    descAr: "حفل تخرّج جامعة الباحة لعام 2025",
    descEn: "Graduation Ceremony of Al-Baha University 2025",
    image: "https://wodohalroya.com/wp-content/uploads/2025/05/56122ac9-62e4-4c0a-ab80-b1d1a016511c-768x513.jpeg",
  },
  {
    id: "bahja",
    titleAr: "بهجة",
    titleEn: "Bahja Festival",
    client: "الهيئة العامة للترفيه",
    category: "events",
    year: 2025,
    descAr: "تنظيم فعاليات بهجة في نسختها الثانية",
    descEn: "Organizing Bahja festival 2nd edition",
    image: "https://wodohalroya.com/wp-content/uploads/2025/05/54a87994-8578-4f13-949c-3c35aba7f751-768x512.jpeg",
  },
];

export const stats: Stat[] = [
  { value: 15, suffix: "+", labelAr: "سنوات من الخبرة", labelEn: "Years of Experience" },
  { value: 500, suffix: "+", labelAr: "مشروع منجز", labelEn: "Projects Completed" },
  { value: 100, suffix: "+", labelAr: "عميل", labelEn: "Clients" },
  { value: 50, suffix: "+", labelAr: "موظف", labelEn: "Employees" },
];

export const values: Value[] = [
  {
    titleAr: "خدمة العملاء",
    titleEn: "Customer Service",
    descAr: "خدمة العملاء هي عنصر حيوي لأي عمل ناجح، تعكس قدرة الشركة على تلبية احتياجات العملاء وتقديم الدعم قبل وأثناء وبعد الخدمة",
    descEn: "Customer service is a vital component of any successful business, reflecting our ability to meet needs and provide support",
    icon: "HeadphonesIcon",
  },
  {
    titleAr: "الجودة",
    titleEn: "Quality",
    descAr: "الالتزام بالتميز ينعكس في كل تفصيل من التخطيط والتصميم إلى التنفيذ والتسليم، نعطي الأولوية للدقة والاتساق",
    descEn: "Commitment to excellence reflected in every detail from planning and design to execution and delivery",
    icon: "Award",
  },
  {
    titleAr: "الإخلاص",
    titleEn: "Sincerity",
    descAr: "الإخلاص هو جودة الصدق والأمانة والابتعاد عن الخداع، ويلعب دوراً رئيسياً في بناء الثقة والعلاقات الهادفة",
    descEn: "Sincerity is the quality of being genuine and honest, playing a key role in building trust and meaningful relationships",
    icon: "Heart",
  },
  {
    titleAr: "الكوادر البشرية",
    titleEn: "Workforce",
    descAr: "نستثمر في فريق عمل محترف يمتلك المهارات والخبرات اللازمة لتقديم أفضل النتائج",
    descEn: "We invest in a professional workforce with the skills and expertise needed to deliver the best results",
    icon: "Users",
  },
  {
    titleAr: "التعلم المستمر",
    titleEn: "Learning",
    descAr: "التعلم والتعليم عمليتان مترابطتان تشكلان أساس التطور والنمو الشخصي والمهني",
    descEn: "Learning and teaching are interconnected processes that form the foundation of personal and professional growth",
    icon: "BookOpen",
  },
];

export const siteConfig = {
  name: "وضوح الرؤية للدعاية والإعلان",
  nameEn: "Wodoh Alroya",
  email: "info@wodohalroya.com",
  phone: "+966592062706",
  whatsapp: "966592062706",
  social: {
    instagram: "https://www.instagram.com/wodohalroya",
    twitter: "https://twitter.com/wodohalroya",
    snapchat: "https://www.snapchat.com/add/wodohalroya",
    tiktok: "https://www.tiktok.com/@wodohalroya1",
    linkedin: "https://www.linkedin.com/company/wodohalroya",
    youtube: "https://www.youtube.com/@wodohalroya",
  },
};
